// Invite code format: STAGE-YYYYMMDD
// e.g. "PREGNANCY-20251225", "NEWMOM-20250801", "TTC-20250603", "TTC"
//
// Generated by the woman's app on PartnerInviteScreen.
// Decoded by the partner's app on UserTypeScreen.
// No backend needed — the code carries all the context the partner needs.

export type InvitePayload = {
  stage: string;
  date?: string;   // ISO YYYY-MM-DD (dueDate for pregnancy, babyDOB for newmom, LMP for ttc)
};

const VALID_STAGES = ['pregnancy', 'newmom', 'ttc'];

export function generateInviteCode(stage: string, date?: string): string {
  const parts = [stage.toUpperCase()];
  if (date) {
    // Store as compact YYYYMMDD
    parts.push(date.replace(/-/g, ''));
  }
  return parts.join('-');
}

export function parseInviteCode(raw: string): InvitePayload | null {
  if (!raw?.trim()) return null;
  const parts = raw.trim().toUpperCase().split('-');
  const stage = parts[0].toLowerCase();
  if (!VALID_STAGES.includes(stage)) return null;

  // Reassemble the rest (date may itself contain dashes when YYYY-MM-DD typed by user)
  const datePart = parts.slice(1).join('');
  let date: string | undefined;

  if (datePart.length === 8) {
    // YYYYMMDD compact form
    date = `${datePart.slice(0, 4)}-${datePart.slice(4, 6)}-${datePart.slice(6, 8)}`;
    // Basic validity check
    const d = new Date(date);
    if (isNaN(d.getTime())) date = undefined;
  }

  return { stage, date };
}
