// Mapping from Lucide icon names to Mingcute icon names + variant
// Used to aid migration; eventually this file can be deleted once all
// usages are migrated to <Icon name="..." /> directly.

export const LUCIDE_TO_MG: Record<string, { name: string; variant?: 'line' | 'fill' }> = {
  Activity:       { name: 'heartbeat' },
  AlertCircle:    { name: 'alert' },
  AlertTriangle:  { name: 'warning' },
  ArrowLeft:      { name: 'arrow_left' },
  ArrowUp:        { name: 'arrow_up' },
  Baby:           { name: 'baby' },
  Bookmark:       { name: 'bookmark' },
  BookmarkCheck:  { name: 'bookmark_edit' },
  CalendarDays:   { name: 'calendar_2' },
  CalendarHeart:  { name: 'calendar' },
  Camera:         { name: 'camera' },
  Car:            { name: 'car_2' },
  Check:          { name: 'check' },
  CheckCircle2:   { name: 'check_circle' },
  ChevronDown:    { name: 'down' },
  ChevronLeft:    { name: 'left' },
  ChevronRight:   { name: 'right' },
  ChevronUp:      { name: 'up' },
  Circle:         { name: 'circle_dash' },
  Clock:          { name: 'time' },
  CornerUpLeft:   { name: 'corner_up_left' },
  FileText:       { name: 'file' },
  Flame:          { name: 'flame' },
  Gift:           { name: 'gift' },
  Heart:          { name: 'heart' },
  HeartPulse:     { name: 'heartbeat_2' },
  Home:           { name: 'home_3' },
  ImagePlus:      { name: 'pic_2' },
  Info:           { name: 'information' },
  Lightbulb:      { name: 'bulb' },
  MapPin:         { name: 'map_pin' },
  MessageCircle:  { name: 'chat_1' },
  Mic:            { name: 'mic' },
  Minus:          { name: 'minus_circle' },
  Navigation:     { name: 'navigation' },
  NotebookPen:    { name: 'notebook' },
  Pencil:         { name: 'pencil' },
  Phone:          { name: 'phone' },
  Plus:           { name: 'add' },
  Repeat:         { name: 'repeat' },
  RotateCcw:      { name: 'refresh_anticlockwise_1' },
  Send:           { name: 'send' },
  Share2:         { name: 'share_2' },
  Shield:         { name: 'shield' },
  ShieldCheck:    { name: 'safety_certificate' },
  ShoppingBag:    { name: 'shopping_bag_1' },
  ShoppingCart:   { name: 'shopping_cart_1' },
  Siren:          { name: 'alarm_1' },
  Square:         { name: 'square' },
  Stethoscope:    { name: 'stethoscope' },
  Trash2:         { name: 'delete_2' },
  TrendingUp:     { name: 'trending_up' },
  X:              { name: 'close' },
};
